// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiV1KraftvaerkUmbracoAlchemyExampleData, GetApiV1KraftvaerkUmbracoAlchemyExampleErrors, GetApiV1KraftvaerkUmbracoAlchemyExampleResponses, PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyData, PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyErrors, PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyResponses, PostApiV1KraftvaerkUmbracoAlchemyBrewData, PostApiV1KraftvaerkUmbracoAlchemyBrewErrors, PostApiV1KraftvaerkUmbracoAlchemyBrewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiV1KraftvaerkUmbracoAlchemyBrew = <ThrowOnError extends boolean = false>(options?: Options<PostApiV1KraftvaerkUmbracoAlchemyBrewData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiV1KraftvaerkUmbracoAlchemyBrewResponses, PostApiV1KraftvaerkUmbracoAlchemyBrewErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/Kraftvaerk.Umbraco.Alchemy/brew',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const postApiV1KraftvaerkUmbracoAlchemyBrewContextByKey = <ThrowOnError extends boolean = false>(options: Options<PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyResponses, PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/Kraftvaerk.Umbraco.Alchemy/brew/context/{key}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getApiV1KraftvaerkUmbracoAlchemyExample = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1KraftvaerkUmbracoAlchemyExampleData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiV1KraftvaerkUmbracoAlchemyExampleResponses, GetApiV1KraftvaerkUmbracoAlchemyExampleErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/Kraftvaerk.Umbraco.Alchemy/example',
        ...options
    });
};
