// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44360' | (string & {});
};

export type BrewPropertyContext = {
    documentTypeName: string;
    documentTypeAlias?: string | null;
    documentTypeDescription?: string | null;
    isElementType?: boolean;
    targetPropertyAlias: string;
    targetPropertyName?: string | null;
    targetPropertyContainerName?: string | null;
    targetPropertyContainerType?: string | null;
    allProperties: Array<BrewPropertyInfo>;
};

export type BrewPropertyInfo = {
    name: string;
    alias: string;
    description?: string | null;
    containerName?: string | null;
    containerType?: string | null;
};

export type BrewRequestModel = {
    prompt: string;
    contextAlias?: string | null;
    propertyContext?: BrewPropertyContext | null;
    cacheKey?: string | null;
    targetPropertyAlias?: string | null;
};

export type BrewResponseModel = {
    result: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewData = {
    body?: BrewRequestModel;
    path?: never;
    query?: never;
    url: '/api/v1/Kraftvaerk.Umbraco.Alchemy/brew';
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewError = PostApiV1KraftvaerkUmbracoAlchemyBrewErrors[keyof PostApiV1KraftvaerkUmbracoAlchemyBrewErrors];

export type PostApiV1KraftvaerkUmbracoAlchemyBrewResponses = {
    /**
     * OK
     */
    200: BrewResponseModel;
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewResponse = PostApiV1KraftvaerkUmbracoAlchemyBrewResponses[keyof PostApiV1KraftvaerkUmbracoAlchemyBrewResponses];

export type PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyData = {
    body?: BrewPropertyContext;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/v1/Kraftvaerk.Umbraco.Alchemy/brew/context/{key}';
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyResponse = PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyResponses[keyof PostApiV1KraftvaerkUmbracoAlchemyBrewContextByKeyResponses];

export type GetApiV1KraftvaerkUmbracoAlchemyExampleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Kraftvaerk.Umbraco.Alchemy/example';
};

export type GetApiV1KraftvaerkUmbracoAlchemyExampleErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetApiV1KraftvaerkUmbracoAlchemyExampleResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiV1KraftvaerkUmbracoAlchemyExampleResponse = GetApiV1KraftvaerkUmbracoAlchemyExampleResponses[keyof GetApiV1KraftvaerkUmbracoAlchemyExampleResponses];
